export * from "./adjective.js";
export * from "./and.js";
export * from "./andor.js";
export * from "./fraction.js";
export * from "./noun.js";
export * from "./number.js";
export * from "./or.js";
export * from "./sentence.js";
export * from "./verb.js";
